import { TileKind } from "../match3/types";

export const ASSET_KEYS = {
  boss: {
    intro: "safira_intro",
    introBack: "safira_intro_back",
    main: "safira_main",
    mainBack: "safira_main_back",
    attack: "safira_attack",
    attackBack: "safira_attack_back",
    ulta: "safira_ulta",
    ultaBack: "safira_ulta_back",
    lowhp: "safira_lowhp",
    lowhpBack: "safira_lowhp_back",
    shield: "boss_shield",
  },
  intro: {
    background: "intro_background",
    vsLogo: "intro_vs",
    swords: "intro_swords",
    swordsGloom: "intro_swords_gloom",
    playerGloom: "intro_player_gloom",
    playerFrame: "player_frame",
    playerNameplate: "player_nameplate",
  },
  game: {
    background: "game_background",
  },
  player: {
    avatar: "player_avatar",
  },
  tiles: {
    [TileKind.Sword]: "tile_sword",
    [TileKind.Star]: "tile_star",
    [TileKind.Mana]: "tile_mana",
    [TileKind.Heal]: "tile_heal",
    [TileKind.BoosterRow]: "tile_booster_row",
    [TileKind.BoosterCol]: "tile_booster_col",
    [TileKind.Ultimate]: "tile_ultimate",
    [TileKind.Bomb]: "tile_bomb",
  },
  glow: {
    gold: "tile_glow_gold",
    red: "tile_glow_red",
  },
  particle: "particle",
  sfx: {
    swap: "sfx_swap",
    swapFail: "sfx_swap_fail",
    match: "sfx_match",
    cascade: "sfx_cascade",
    specialCreate: "sfx_special_create",
    specialActivate: "sfx_special_activate",
    tileCollapse: "sfx_tile_collapse",
    bossHit: "sfx_boss_hit",
    playerHit: "sfx_player_hit",
    shieldBlock: "sfx_shield_block",
    heal: "sfx_heal",
    mana: "sfx_mana",
    skill: "sfx_skill",
    hammer: "sfx_hammer",
    bossAttack: "sfx_boss_attack",
    abilityAnnounce: "sfx_ability_announce",
    bombPlace: "sfx_bomb_place",
    bombExplode: "sfx_bomb_explode",
    bombDefuse: "sfx_bomb_defuse",
    shieldActivate: "sfx_shield_activate",
    manaDrain: "sfx_mana_drain",
    victory: "sfx_victory",
    defeat: "sfx_defeat",
    vs: "sfx_vs",
  },
};
