/**
 * ArenaPerkModal -- blocking perk selection modal for arena fights.
 *
 * Opened by GameScene after a boss HP layer break (via injected
 * `arenaPerkModal.open()` callback). Shows 3 perk cards generated by
 * ArenaPerkSystem.getCardOptions(). Player MUST pick one -- no dismiss.
 *
 * Visual quality matches v1 PerkCard: Graphics-based fillRoundedRect,
 * glow borders with alpha tweens, title strips, star rows, icons, and
 * entrance/selection animations.
 *
 * Depth 2100 (blocking modal layer per R2B-3).
 * Zero GameScene imports -- receives scene as unknown, casts to Phaser.Scene.
 */

import Phaser from "phaser";
import { arenaPerkSystem } from "../systems/ArenaPerkSystem";
import type { PerkCard, SkillPerkCard } from "../systems/ArenaPerkSystem";
import { V2_FONTS } from "./theme";
import { DPR } from "../../game/config";
import { MAX_PERK_LEVEL } from "../../game/PerkManager";

const MODAL_DEPTH = 2100;
const CARD_WIDTH = 130;
const CARD_HEIGHT = 190;
const CARD_GAP = 10;
const CARD_RADIUS = 12;

const STAR_CHAR = "\u2605"; // filled star
const STAR_EMPTY_CHAR = "\u2606"; // empty star

/** Per-type color sets matching the v1 PerkCard visual language. */
const TYPE_COLORS = {
  skill: {
    border: 0xd4a017,
    borderGlow: 0xffd700,
    titleBg: 0x2a1a0e,
    title: "#ffd700",
  },
  passive: {
    border: 0x7733aa,
    borderGlow: 0x9944aa,
    titleBg: 0x1e0e2e,
    title: "#cc88ee",
  },
  stat: {
    border: 0x338844,
    borderGlow: 0x44aa66,
    titleBg: 0x0e1e0e,
    title: "#66dd88",
  },
} as const;

const SHARED_COLORS = {
  bg: 0x1a1a2e,
  starFilled: "#ffd700",
  starEmpty: "#444466",
  icon: "#ffffff",
  description: "#cccccc",
  manaCost: "#aabbff",
  badge: "#bbbbdd",
} as const;

/**
 * Open a blocking perk modal on the given scene. Returns a Promise that
 * resolves after the player picks a card and the card is applied.
 */
export function openArenaPerkModal(rawScene: unknown): Promise<void> {
  const scene = rawScene as Phaser.Scene;
  const cards = arenaPerkSystem.getCardOptions();
  if (cards.length === 0) return Promise.resolve();

  return new Promise<void>((resolve) => {
    const d = DPR;
    const camW = scene.cameras.main.width / d;
    const camH = scene.cameras.main.height / d;
    const cx = camW / 2;

    /** All GameObjects created by the modal -- destroyed on resolve. */
    const objects: Phaser.GameObjects.GameObject[] = [];
    /** All tweens -- stopped on cleanup to prevent orphan callbacks. */
    const tweens: Phaser.Tweens.Tween[] = [];
    /** Card containers for entrance/selection animations. */
    const cardContainers: Phaser.GameObjects.Container[] = [];

    let picked = false; // guard against double-tap

    // ── Dark overlay ──────────────────────────────────────────────────────
    const overlay = scene.add
      .rectangle(0, 0, camW, camH, 0x000000, 0.75)
      .setOrigin(0)
      .setDepth(MODAL_DEPTH)
      .setInteractive(); // blocks clicks through
    objects.push(overlay);

    // ── Title ─────────────────────────────────────────────────────────────
    const title = scene.add
      .text(cx, camH * 0.18, "Выбери улучшение", {
        fontSize: "22px",
        color: "#ffd700",
        fontFamily: V2_FONTS.primary,
        fontStyle: "bold",
        stroke: "#000000",
        strokeThickness: 3,
        resolution: 2,
      })
      .setOrigin(0.5)
      .setDepth(MODAL_DEPTH + 1);
    objects.push(title);

    // ── Subtitle ──────────────────────────────────────────────────────────
    const sub = scene.add
      .text(cx, camH * 0.18 + 28, "Нажми на карточку", {
        fontSize: "12px",
        color: "#9f7fc7",
        fontFamily: V2_FONTS.primary,
        fontStyle: "italic",
        resolution: 2,
      })
      .setOrigin(0.5)
      .setDepth(MODAL_DEPTH + 1);
    objects.push(sub);

    // ── Cards layout ──────────────────────────────────────────────────────
    const totalW = cards.length * CARD_WIDTH + (cards.length - 1) * CARD_GAP;
    const startX = cx - totalW / 2 + CARD_WIDTH / 2;
    const cardY = camH * 0.50;
    const scale = CARD_HEIGHT / 200; // scale factor relative to base 200px
    const halfW = CARD_WIDTH / 2;
    const halfH = CARD_HEIGHT / 2;

    cards.forEach((card, idx) => {
      const cardX = startX + idx * (CARD_WIDTH + CARD_GAP);
      const colors = TYPE_COLORS[card.type];

      // Container for this card -- all children positioned relative to (0,0)
      const container = scene.add.container(cardX, cardY);
      container.setDepth(MODAL_DEPTH + 1);
      container.setScale(0);
      container.setAlpha(0);
      objects.push(container);
      cardContainers.push(container);

      // ── Glow border (behind card, slightly larger) ────────────────────
      const borderGlow = scene.add.graphics();
      borderGlow.lineStyle(4, colors.borderGlow, 0.6);
      borderGlow.strokeRoundedRect(
        -halfW - 2, -halfH - 2,
        CARD_WIDTH + 4, CARD_HEIGHT + 4,
        CARD_RADIUS + 2,
      );
      borderGlow.setAlpha(0.4);
      container.add(borderGlow);

      // Glow pulse tween
      const glowTween = scene.tweens.add({
        targets: borderGlow,
        alpha: { from: 0.4, to: 0.8 },
        duration: 1200,
        yoyo: true,
        repeat: -1,
        ease: "Sine.easeInOut",
      });
      tweens.push(glowTween);

      // ── Card background ───────────────────────────────────────────────
      const cardBg = scene.add.graphics();
      cardBg.fillStyle(SHARED_COLORS.bg, 0.95);
      cardBg.fillRoundedRect(-halfW, -halfH, CARD_WIDTH, CARD_HEIGHT, CARD_RADIUS);
      cardBg.lineStyle(2, colors.border, 0.9);
      cardBg.strokeRoundedRect(-halfW, -halfH, CARD_WIDTH, CARD_HEIGHT, CARD_RADIUS);
      container.add(cardBg);

      // ── Title strip ───────────────────────────────────────────────────
      const titleH = Math.round(26 * scale);
      const titleGfx = scene.add.graphics();
      titleGfx.fillStyle(
        typeof colors.titleBg === "number" ? colors.titleBg : 0x2a1a0e,
        0.9,
      );
      titleGfx.fillRoundedRect(-halfW, -halfH, CARD_WIDTH, titleH, {
        tl: CARD_RADIUS,
        tr: CARD_RADIUS,
        bl: 0,
        br: 0,
      });
      container.add(titleGfx);

      // ── Title text ────────────────────────────────────────────────────
      const titleText = scene.add
        .text(0, -halfH + titleH / 2, card.name, {
          fontSize: `${Math.round(14 * scale)}px`,
          color: colors.title,
          fontFamily: V2_FONTS.primary,
          fontStyle: "bold",
          stroke: "#000000",
          strokeThickness: 2,
          resolution: 2,
          wordWrap: { width: CARD_WIDTH - 12 },
          align: "center",
        })
        .setOrigin(0.5);
      container.add(titleText);

      // ── Icon circle ───────────────────────────────────────────────────
      const iconY = -halfH + titleH + Math.round(38 * scale);
      const circleR = Math.round(28 * scale);
      const iconCircle = scene.add.graphics();
      iconCircle.fillStyle(0x2a2a4a, 0.9);
      iconCircle.fillCircle(0, iconY, circleR);
      iconCircle.lineStyle(2, 0x4a4a8a, 0.8);
      iconCircle.strokeCircle(0, iconY, circleR);
      container.add(iconCircle);

      const iconEmoji = getCardIcon(card);
      const iconText = scene.add
        .text(0, iconY, iconEmoji, {
          fontSize: `${Math.round(30 * scale)}px`,
          color: SHARED_COLORS.icon,
          fontFamily: V2_FONTS.primary,
          resolution: 2,
        })
        .setOrigin(0.5);
      container.add(iconText);

      // ── Middle section: stars / badge / count ─────────────────────────
      const middleY = iconY + Math.round(50 * scale);
      buildMiddleSection(scene, container, card, middleY, scale, tweens);

      // ── Description ───────────────────────────────────────────────────
      const descY = halfH - Math.round(24 * scale);
      const descText = scene.add
        .text(0, descY, card.description, {
          fontSize: `${Math.round(11 * scale)}px`,
          color: SHARED_COLORS.description,
          fontFamily: V2_FONTS.primary,
          fontStyle: "italic",
          align: "center",
          wordWrap: { width: CARD_WIDTH - 16 },
          resolution: 2,
        })
        .setOrigin(0.5);
      container.add(descText);

      // ── Hit area (invisible interactive rect) ─────────────────────────
      const hitArea = scene.add
        .rectangle(0, 0, CARD_WIDTH, CARD_HEIGHT, 0x000000, 0)
        .setInteractive({ useHandCursor: true });
      container.add(hitArea);

      // ── Hover effects ─────────────────────────────────────────────────
      hitArea.on("pointerover", () => {
        if (picked) return;
        const t = scene.tweens.add({
          targets: borderGlow,
          alpha: 0.9,
          duration: 150,
          ease: "Quad.easeOut",
        });
        tweens.push(t);
      });
      hitArea.on("pointerout", () => {
        if (picked) return;
        const t = scene.tweens.add({
          targets: borderGlow,
          alpha: 0.4,
          duration: 150,
          ease: "Quad.easeOut",
        });
        tweens.push(t);
      });

      // ── Click: apply perk and close ───────────────────────────────────
      hitArea.on("pointerdown", () => {
        if (picked) return;
        picked = true;

        arenaPerkSystem.applyCard(card);

        // Selection animation: picked card scales up + glows, others fade out
        const selectedIdx = idx;
        const promises: Promise<void>[] = [];

        cardContainers.forEach((c, ci) => {
          if (ci === selectedIdx) {
            promises.push(playSelect(scene, c, tweens));
          } else {
            promises.push(playDismiss(scene, c, tweens));
          }
        });
        // Fade overlay + title
        const fadeTween = scene.tweens.add({
          targets: [overlay, title, sub],
          alpha: 0,
          duration: 200,
          ease: "Quad.easeIn",
        });
        tweens.push(fadeTween);

        Promise.all(promises).then(() => {
          cleanup(objects, tweens);
          resolve();
        });
      });
    });

    // ── Entrance animation: staggered scale-in per card ───────────────────
    cardContainers.forEach((c, i) => {
      const t = scene.tweens.add({
        targets: c,
        scale: { from: 0, to: 1 },
        alpha: { from: 0, to: 1 },
        duration: 300,
        delay: i * 100,
        ease: "Back.easeOut",
      });
      tweens.push(t);
    });

    // Fade in overlay + titles (individual tweens for different alpha targets)
    overlay.setAlpha(0);
    title.setAlpha(0);
    sub.setAlpha(0);
    const oFade = scene.tweens.add({
      targets: overlay,
      alpha: 0.75,
      duration: 250,
      ease: "Quad.easeOut",
    });
    const tFade = scene.tweens.add({
      targets: title,
      alpha: 1,
      duration: 250,
      ease: "Quad.easeOut",
    });
    const sFade = scene.tweens.add({
      targets: sub,
      alpha: 1,
      duration: 250,
      ease: "Quad.easeOut",
    });
    tweens.push(oFade, tFade, sFade);
  });
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getCardIcon(card: PerkCard): string {
  switch (card.type) {
    case "skill": return card.icon;
    case "passive": return "\u2726"; // "star-like" default icon
    case "stat": return "\u25B2"; // triangle-up
  }
}

/**
 * Build the middle section between icon and description:
 * - skill: 5-star row with blinking "next" star
 * - passive: "one-time" badge text
 * - stat: "x{count+1}" badge
 */
function buildMiddleSection(
  scene: Phaser.Scene,
  container: Phaser.GameObjects.Container,
  card: PerkCard,
  y: number,
  scale: number,
  tweens: Phaser.Tweens.Tween[],
): void {
  if (card.type === "skill") {
    buildStarRow(scene, container, card, y, scale, tweens);
    return;
  }

  if (card.type === "passive") {
    const badge = scene.add
      .text(0, y, "Одноразовый", {
        fontSize: `${Math.round(10 * scale)}px`,
        color: SHARED_COLORS.badge,
        fontFamily: V2_FONTS.primary,
        fontStyle: "italic",
        resolution: 2,
      })
      .setOrigin(0.5);
    container.add(badge);
    return;
  }

  // stat card
  if (card.type === "stat") {
    const countLabel = card.currentCount > 0
      ? `\u00d7${card.currentCount + 1}`
      : "";
    if (countLabel) {
      const countText = scene.add
        .text(0, y, countLabel, {
          fontSize: `${Math.round(16 * scale)}px`,
          color: TYPE_COLORS.stat.title,
          fontFamily: V2_FONTS.primary,
          fontStyle: "bold",
          resolution: 2,
        })
        .setOrigin(0.5);
      container.add(countText);
    }
  }
}

/** Render a 5-star row for skill perk cards. */
function buildStarRow(
  scene: Phaser.Scene,
  container: Phaser.GameObjects.Container,
  card: SkillPerkCard,
  y: number,
  scale: number,
  tweens: Phaser.Tweens.Tween[],
): void {
  const starCount = MAX_PERK_LEVEL;
  const starSpacing = Math.round(16 * scale);
  const startX = -(starSpacing * (starCount - 1)) / 2;

  for (let i = 0; i < starCount; i++) {
    const isFilled = i < card.currentLevel;
    const isNext = i === card.currentLevel;
    const char = isFilled || isNext ? STAR_CHAR : STAR_EMPTY_CHAR;
    const color = isFilled
      ? SHARED_COLORS.starFilled
      : isNext
        ? SHARED_COLORS.starFilled
        : SHARED_COLORS.starEmpty;

    const star = scene.add
      .text(startX + i * starSpacing, y, char, {
        fontSize: `${Math.round(14 * scale)}px`,
        color,
        fontFamily: V2_FONTS.primary,
        resolution: 2,
      })
      .setOrigin(0.5);
    container.add(star);

    // Blink animation for the "next level" star
    if (isNext) {
      const blinkTween = scene.tweens.add({
        targets: star,
        alpha: { from: 0.3, to: 1 },
        duration: 500,
        yoyo: true,
        repeat: -1,
        ease: "Sine.easeInOut",
      });
      tweens.push(blinkTween);
    }
  }
}

/** Selected card scales up, glows, then fades out. */
function playSelect(
  scene: Phaser.Scene,
  container: Phaser.GameObjects.Container,
  tweens: Phaser.Tweens.Tween[],
): Promise<void> {
  // Bring selected card above its siblings so the zoom isn't clipped by neighbors.
  container.setDepth(MODAL_DEPTH + 5);
  return new Promise<void>((resolve) => {
    if (!scene || !scene.tweens) { resolve(); return; }
    const t1 = scene.tweens.add({
      targets: container,
      scale: 1.15,
      duration: 150,
      ease: "Quad.easeOut",
      onComplete: () => {
        if (!scene || !scene.tweens) { resolve(); return; }
        const t2 = scene.tweens.add({
          targets: container,
          alpha: 0,
          scale: 1.3,
          duration: 200,
          ease: "Quad.easeIn",
          onComplete: () => resolve(),
        });
        tweens.push(t2);
      },
    });
    tweens.push(t1);
  });
}

/** Non-selected cards shrink and fade out. */
function playDismiss(
  scene: Phaser.Scene,
  container: Phaser.GameObjects.Container,
  tweens: Phaser.Tweens.Tween[],
): Promise<void> {
  return new Promise<void>((resolve) => {
    if (!scene || !scene.tweens) { resolve(); return; }
    const t = scene.tweens.add({
      targets: container,
      alpha: 0,
      scale: 0.8,
      duration: 200,
      ease: "Quad.easeIn",
      onComplete: () => resolve(),
    });
    tweens.push(t);
  });
}

/** Destroy all objects and stop all tweens. */
function cleanup(
  objects: Phaser.GameObjects.GameObject[],
  tweens: Phaser.Tweens.Tween[],
): void {
  for (const tw of tweens) {
    if (tw && !tw.isDestroyed()) tw.stop();
  }
  for (const obj of objects) {
    if (obj && "destroy" in obj) {
      (obj as Phaser.GameObjects.GameObject).destroy();
    }
  }
}
