/**
 * ArenaPerkModal — blocking perk selection modal for arena fights.
 *
 * Opened by GameScene after a boss HP layer break (via injected
 * `arenaPerkModal.open()` callback). Shows 3 perk cards generated by
 * ArenaPerkSystem.getCardOptions(). Player MUST pick one — no dismiss.
 *
 * Depth 2100 (blocking modal layer per R2B-3).
 * Zero GameScene imports — receives scene as unknown, casts to Phaser.Scene.
 */

import Phaser from "phaser";
import { arenaPerkSystem } from "../systems/ArenaPerkSystem";
import type { PerkCard } from "../systems/ArenaPerkSystem";
import { V2_COLORS, V2_FONTS } from "./theme";
import { DPR } from "../../game/config";

const MODAL_DEPTH = 2100;
const CARD_WIDTH = 130;
const CARD_HEIGHT = 180;
const CARD_GAP = 10;

const CARD_COLORS: Record<PerkCard["type"], number> = {
  skill: 0x3355cc,
  passive: 0x9944aa,
  stat: 0x667744,
};

/**
 * Open a blocking perk modal on the given scene. Returns a Promise that
 * resolves after the player picks a card and the card is applied.
 */
export function openArenaPerkModal(rawScene: unknown): Promise<void> {
  const scene = rawScene as Phaser.Scene;
  const cards = arenaPerkSystem.getCardOptions();
  if (cards.length === 0) return Promise.resolve();

  return new Promise<void>((resolve) => {
    const d = DPR;
    const camW = scene.cameras.main.width / d;
    const camH = scene.cameras.main.height / d;
    const cx = camW / 2;
    const objects: Phaser.GameObjects.GameObject[] = [];

    // Dark overlay
    const overlay = scene.add
      .rectangle(0, 0, camW, camH, 0x000000, 0.75)
      .setOrigin(0)
      .setDepth(MODAL_DEPTH)
      .setInteractive(); // block clicks through
    objects.push(overlay);

    // Title
    const title = scene.add
      .text(cx, camH * 0.18, "Выбери перк", {
        fontSize: `${22}px`,
        color: "#ffd700",
        fontFamily: V2_FONTS.primary,
        fontStyle: "bold",
        stroke: "#000000",
        strokeThickness: 3,
      })
      .setOrigin(0.5)
      .setDepth(MODAL_DEPTH + 1);
    objects.push(title);

    // Subtitle
    const sub = scene.add
      .text(cx, camH * 0.18 + 30, "Нажми на карточку", {
        fontSize: `${12}px`,
        color: V2_COLORS.subtitleColor,
        fontFamily: V2_FONTS.primary,
        fontStyle: "italic",
      })
      .setOrigin(0.5)
      .setDepth(MODAL_DEPTH + 1);
    objects.push(sub);

    // Cards
    const totalW = cards.length * CARD_WIDTH + (cards.length - 1) * CARD_GAP;
    const startX = cx - totalW / 2 + CARD_WIDTH / 2;
    const cardY = camH * 0.5;

    cards.forEach((card, idx) => {
      const cardX = startX + idx * (CARD_WIDTH + CARD_GAP);
      const borderColor = CARD_COLORS[card.type] ?? 0x666666;

      const bg = scene.add
        .rectangle(cardX, cardY, CARD_WIDTH, CARD_HEIGHT, 0x1a1a2e, 0.95)
        .setStrokeStyle(2, borderColor)
        .setDepth(MODAL_DEPTH + 1)
        .setInteractive({ useHandCursor: true });
      objects.push(bg);

      // Type badge
      const badgeText = card.type === "skill" ? "⚔ Скил"
        : card.type === "passive" ? "✦ Пассивка"
        : "▲ Стат";
      const badge = scene.add
        .text(cardX, cardY - CARD_HEIGHT / 2 + 16, badgeText, {
          fontSize: `${10}px`,
          color: "#aaaacc",
          fontFamily: V2_FONTS.primary,
        })
        .setOrigin(0.5)
        .setDepth(MODAL_DEPTH + 2);
      objects.push(badge);

      // Name
      const name = scene.add
        .text(cardX, cardY - 30, card.name, {
          fontSize: `${14}px`,
          color: "#ffffff",
          fontFamily: V2_FONTS.primary,
          fontStyle: "bold",
          wordWrap: { width: CARD_WIDTH - 16 },
          align: "center",
        })
        .setOrigin(0.5)
        .setDepth(MODAL_DEPTH + 2);
      objects.push(name);

      // Description
      const desc = scene.add
        .text(cardX, cardY + 15, card.description, {
          fontSize: `${10}px`,
          color: V2_COLORS.bodyColor,
          fontFamily: V2_FONTS.primary,
          wordWrap: { width: CARD_WIDTH - 16 },
          align: "center",
        })
        .setOrigin(0.5)
        .setDepth(MODAL_DEPTH + 2);
      objects.push(desc);

      // Extra info per type
      let extraText = "";
      if (card.type === "skill") {
        const stars = "★".repeat(card.nextLevel) + "☆".repeat(Math.max(0, 5 - card.nextLevel));
        extraText = `${card.icon} ${stars}`;
      } else if (card.type === "stat") {
        extraText = card.currentCount > 0 ? `×${card.currentCount + 1}` : "";
      }
      if (extraText) {
        const extra = scene.add
          .text(cardX, cardY + CARD_HEIGHT / 2 - 18, extraText, {
            fontSize: `${11}px`,
            color: "#e6c068",
            fontFamily: V2_FONTS.primary,
            fontStyle: "bold",
          })
          .setOrigin(0.5)
          .setDepth(MODAL_DEPTH + 2);
        objects.push(extra);
      }

      // Hover effects
      bg.on("pointerover", () => bg.setFillStyle(0x2a2a4e, 1));
      bg.on("pointerout", () => bg.setFillStyle(0x1a1a2e, 0.95));

      // Click — apply perk and close
      bg.on("pointerdown", () => {
        arenaPerkSystem.applyCard(card);
        // Cleanup all objects
        for (const obj of objects) {
          if (obj && "destroy" in obj) {
            (obj as Phaser.GameObjects.GameObject).destroy();
          }
        }
        resolve();
      });
    });

    // Entrance animation — fade in all objects
    for (const obj of objects) {
      if ("setAlpha" in obj) {
        (obj as any).setAlpha(0);
      }
    }
    scene.tweens.add({
      targets: objects,
      alpha: 1,
      duration: 250,
      ease: "Quad.easeOut",
    });
  });
}
