/**
 * GOLD STANDARD: CRIT Multiplier Pattern
 *
 * Replaces the old booster system (BoosterRow/BoosterCol/Ultimate) with
 * CRIT multipliers that enhance tile counts without creating special tiles.
 *
 * 1. CONFIG CONSTANTS
 *    - CRIT thresholds defined in config.ts as CRIT_MULTIPLIERS:
 *
 *      export const CRIT_MULTIPLIERS = {
 *        match4: 2,   // 4-tile match = x2
 *        match5: 3,   // 5+ tile match or L-shape = x3
 *      } as const;
 *
 * 2. BOARD LOGIC (Board.ts)
 *    - Module-level critMultiplier() converts match length to CRIT value:
 *
 *      function critMultiplier(matchLength: number): number {
 *        if (matchLength >= 5) return CRIT_MULTIPLIERS.match5;
 *        if (matchLength >= 4) return CRIT_MULTIPLIERS.match4;
 *        return 1;
 *      }
 *
 *    - computeClearOutcome() creates transforms with multiplier (not booster kind):
 *
 *      transforms.push({
 *        pos: { ...anchorPos },
 *        kind: match.kind,        // stays as BaseTileKind (sword, star, etc.)
 *        base: match.kind,
 *        tile: tileAtPos,
 *        multiplier: critMultiplier(match.positions.length),
 *      });
 *
 *    - Anchor tile survives clearing and retains its base kind + multiplier
 *    - When a CRIT tile is cleared in a future match, counts use multiplier:
 *
 *      counts[tile.base] += tile.multiplier ?? 1;
 *
 *    - applyClearOutcome() preserves highest multiplier on re-transform:
 *
 *      current.multiplier = Math.max(current.multiplier ?? 1, transform.multiplier ?? 1);
 *
 * 3. GAMESCENE RENDERING
 *    - CRIT tiles render as base tile sprite + glow overlay
 *    - Glow color: gold (4-match), red (5+) via ASSET_KEYS.glow.gold/red
 *    - "CRIT! x2" / "MEGA CRIT! x3" floating text on creation
 *    - No special tile sprites needed (no BoosterRow/Col/Ultimate textures)
 *
 * 4. L-SHAPE HANDLING
 *    - L-shape = two matches of same kind sharing a corner position
 *    - Always 5+ unique positions, so always x3 CRIT
 *    - Anchor chosen from swap targets or corner position
 *
 * 5. SQUARE MATCH (2x2)
 *    - 4 tiles = x2 CRIT, same as linear 4-match
 *    - Intentional: squares are harder to spot, deserve same reward
 *
 * 6. DEPRECATED TYPES
 *    - TileKind.BoosterRow/BoosterCol/Ultimate still in enum for backward compat
 *    - Marked with @deprecated JSDoc
 *    - Never generated by Board logic
 *    - ASSET_KEYS.tiles entries kept for TypeScript type compatibility
 */
